import random

words = ("January",
         "February",
         "March",
         "April",
         "May",
         "June",
         "July",
         "August",
         "September",
         "October",
         "November",
         "December",
         "Sunday",
         "Monday",
         "Tuesday",
         "Wednesday",
         "Thursday",
         "Friday",
         "Saturday",
         "Big",
         "Small",
         "Large",
         "Round",
         "Square",
         "Xylophone",
         "Power",
         "Zebra",
         "Corgi",
         "Winner",
         "Chicken",
         "Alpha",
         "Number",
         "Letter",
         "Day",
         "Night",
         "Gold",
         "Mold")

word = random.choice(words)